### ISSUE TITLE
Monitoring multiple Nginx instances

### ISSUE THREAD

**Issue by mrkschan** [mrkschan/nginxbeat#1]
It's definitely a need to monitor multiple Nginx instances at a time just like to approach mentioned at https://github.com/elastic/libbeat/issues/37#issuecomment-152861180.

The config file would define a list of servers to be monitored  (each of them may use different formats, i.e. stub v.s. nginx plus; though, let's not get to that complicated things first :tongue:). Nginxbeat would monitor each of them in a tick.

**Comment by mrkschan** [comment]
@ruflin, please correct me if i'm wrong, filebeat is using one go routine per each monitored file. Do you think we can have one go routine per Nginx server here as well?

Since there would not be millions of servers being monitored, having one go routine per server and having a ticker each is the simplest approach that i can think of.

**Comment by ruflin** [comment]
@mrkschan Yes, each harvester is a go routine. I would strongly suggest to have a go routing per nginx server. You will probably have less nginx servers then we have log files. Having go routines makes it also very easy to restart a routing in case of failure.
