### ISSUE TITLE
adopt integration test?

### ISSUE THREAD

**Issue by mrkschan** [mrkschan/nginxbeat#35]

**Comment by ruflin** [comment]
@mrkschan I would be more then happy to support you in this as it would be interesting to see what still needs to change on our side so you can reuse it.

**Comment by mrkschan** [comment]
@ruflin, may I know what do you guys really do in integration test / system test?

As far as I can see from filebeat, 

* It basically runs `main()` inside a docker environment in integration test...
* It runs nosetests in system test and deals with some I/O checking of the beat...

Why do we need docker in integration test but not system test?

Do I miss something?

**Comment by ruflin** [comment]
We split it up in 3 parts:

* Unit tests: Normal Golang unit tests
* Integration tests: Golang unit tests which have external dependencies
* System tests: Written in Python, use file output and run the binary with coverage metrics inside

Real integration tests currently only exist for libbeat and the upcoming metricbeat. All the other tests beats do not rely on an external service to be run. For the same reason, the current system tests do not need any environments running as we use file as output.

The difference here is, that nginxbeat definitively needs and environment for the system tests as it needs nginx to be running. I'm currently working on making this happen in combination with metricbeat and also making the docker environment more flexible / configurable for example with extending docker-compose files. But this is WIP. In the long run I think also the system tests should run inside the container and nginxbeat and metricbeat show that this is almost inevitable. Let me know if some parts above are unclear or you need some more detail.

What do you mean with the docker-compose path?

**Comment by mrkschan** [comment]
So, in case of Nginxbeat,

* Unit test, use mocks.
* Integration test, remove the mocks and use a Nginx process in docker environment.
* System test, build the binary, use a Nginx process in docker environment and test the binary with nosetest.

Am I on the right track?

**Comment by ruflin** [comment]
I like the first approach as it is what we are doing now (except for the docker environment for the system tests, but I'm working on that). The way we solve the separation at the moment is with the short flag. Have a look here: https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/api_integration_test.go#L17

**Comment by mrkschan** [comment]
Hey, @ruflin, I just got the answer to my own question. From stackoverflow [1], I like the idea of using build tag or test function naming convention so that we can separately run unit test and integration test.

[1]: http://stackoverflow.com/questions/25965584/separating-unit-tests-and-integration-tests-in-golang-testify

**Comment by ruflin** [comment]
I quite like the idea of build tags. `-short` was more a short term hack and convenient to use. But I agree we should move in the long term in the direction of build tags or something similar.

**Comment by mrkschan** [comment]
yea, the build tags can unify the way we organize unit test, integration test, and system test without exposing a CLI flag. And, we can still keep using `-short` to ...

> Tell long-running tests to shorten their run time. It is off by default but set during all.bash so that installing the Go tree can run a sanity check but not spend time running exhaustive tests. [1]

[1]: https://golang.org/cmd/go/#hdr-Description_of_testing_flags

**Comment by ruflin** [comment]
Feel free to open an issue in the beats repo for this change to discuss it also with the others. Or let me know in case you changed your repo to use it so we can have a closer look and see if we can just copy / paste it over :-)

**Comment by ruflin** [comment]
PR to introduce build tags in beats: https://github.com/elastic/beats/pull/1073
