### ISSUE TITLE
ERR Invalid Nginx status page format

### ISSUE THREAD

**Issue by 2Fast2BCn** [mrkschan/nginxbeat#44]
### /opt/nginxbeat/nginxbeat -e -c=/opt/nginxbeat/nginxbeat.yml
2016/03/31 08:24:24.441722 nginxbeat.go:60: ERR Invalid Nginx status page format:  is not supported
Start error:  is not supported
2016/03/31 08:24:24.441747 beat.go:115: CRIT Start error:  is not supported
panic: close of nil channel

goroutine 1 [running]:
github.com/mrkschan/nginxbeat/beat.(*Nginxbeat).Stop(0xc82013c000)
        /go/src/github.com/mrkschan/nginxbeat/beat/nginxbeat.go:147 +0x64
github.com/elastic/beats/libbeat/beat.(*Beat).Stop(0xc82013e000)
        /go/src/github.com/elastic/beats/libbeat/beat/beat.go:262 +0x77
github.com/elastic/beats/libbeat/beat.Run(0x8ef470, 0x9, 0x8e3cb0, 0xb, 0x7f18b4f8b028, 0xc82013c000, 0x0, 0x0)
        /go/src/github.com/elastic/beats/libbeat/beat/beat.go:127 +0xd0
main.main()
        /go/src/github.com/mrkschan/nginxbeat/main.go:15 +0xa4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc820001800)
        /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:61 +0x449
created by github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
        /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:55 +0x11e

goroutine 8 [runnable]:
github.com/elastic/beats/libbeat/publisher.(*bulkWorker).run(0xc82007ad20)
        /go/src/github.com/elastic/beats/libbeat/publisher/bulk.go:57 +0x3ca
created by github.com/elastic/beats/libbeat/publisher.newBulkWorker
        /go/src/github.com/elastic/beats/libbeat/publisher/bulk.go:41 +0x20a

### curl http://127.0.0.1:8000/nginx_stub_status
Active connections: 1
server accepts handled requests
 2466 2466 23
Reading: 0 Writing: 1 Waiting: 0

### cat /opt/nginxbeat/nginxbeat.yml
input:
  urls:
    - http://127.0.0.1:8000/nginx_stub_status
  period: 10
output:
  logstash:
    hosts: ["ip:port"]
shipper:
logging:
  to_files: true
  files:
    path: /log/
    name: nginxbeat
    rotateeverybytes: 10485760 # = 10MB

**Comment by thibaultlavoisey** [comment]
+1

**Comment by thibaultlavoisey** [comment]
@2Fast2BCn You need to add `#stub` at the end of the URL.

**Comment by 2Fast2BCn** [comment]
OK cool that does the trick.
Note: I found nginx-module-vts from issue #11 very nice, thx ;-)
