### ISSUE TITLE
Kibana

### ISSUE THREAD

**Issue by JasonIamAUnixAdmin** [mrkschan/nginxbeat#46]
Using Kibana 4.5.1 having loaded the default templates and having loaded data with the beat I am getting this error. 

```
There is a problem with that saved object
The index pattern associated with this object no longer exists.
If you know what this error means, go ahead and fix it - otherwise click the delete button above.
```

Still looking at fixes. Mostly opening this so if the next person finds this they know they are not alone.

**Comment by mrkschan** [comment]
@ruflin any idea?

**Comment by ruflin** [comment]
Which ES version are you using? Did you load the templates for 5.x or 2.x? 

@mrkschan TBH not sure which version of the templates the current version of nginxbeat is providing. Worth trying with metricbeat to see if it is solved?

**Comment by mrkschan** [comment]
@ruflin the template is created with this config - https://github.com/mrkschan/nginxbeat/blob/master/docker-compose.yml#L1-L12

**Comment by ruflin** [comment]
@mrkschan That could be the issue. That is an es and kibana version which is quite a bit older. 

@JasonIamAUnixAdmin Could you test the nginx module in metricbeat to see if this resolves your issue? https://www.elastic.co/downloads/beats/metricbeat

**Comment by JasonIamAUnixAdmin** [comment]
I loaded up metricbeat and have no change. It is however sending to the metricbeat index template and the above error looks to be looking for an index starting with "nginxbeat".

kibanaSavedObjectMeta.searchSourceJSON
```
{
  "index": "[nginxbeat-]YYYY.MM.DD",
  "query": {
    "query_string": {
      "query": "_type:stub",
      "analyze_wildcard": true
    }
  },
  "filter": []
}
```

vistate:
```
{
  "type": "line",
  "params": {
    "shareYAxis": true,
    "addTooltip": true,
    "addLegend": true,
    "showCircles": true,
    "smoothLines": false,
    "interpolate": "linear",
    "scale": "linear",
    "drawLinesBetweenPoints": true,
    "radiusRatio": 9,
    "times": [],
    "addTimeMarker": false,
    "defaultYExtents": false,
    "setYExtents": false,
    "yAxis": {}
  },
  "aggs": [
    {
      "id": "1",
      "type": "sum",
      "schema": "metric",
      "params": {
        "field": "stub.active"
      }
    },
    {
      "id": "2",
      "type": "date_histogram",
      "schema": "segment",
      "params": {
        "field": "@timestamp",
        "interval": "auto",
        "customInterval": "2h",
        "min_doc_count": 1,
        "extended_bounds": {}
      }
    }
  ],
  "listeners": {}
}
```

**Comment by ruflin** [comment]
@JasonIamAUnixAdmin But the metricbeat index works as expected?

**Comment by JasonIamAUnixAdmin** [comment]
@ruflin It is being populated correctly yes. This was about the default Kibana views not working for nginx
